const ctaHref =
  "mailto:pitchdeck@windcore.example?subject=WindCore%20Pitch%20Deck%20Request";

const navLinks = [
  { label: "Problem", href: "#problem" },
  { label: "Blueprint", href: "#blueprint" },
  { label: "Provenance", href: "#provenance" },
  { label: "Orchestration", href: "#orchestration" },
  { label: "Summary", href: "#summary" },
];

const heroStats = [
  { value: "Physical", label: "renewable supply" },
  { value: "Behind meter", label: "compute connection" },
  { value: "Audit grade", label: "workload evidence" },
];

const problemCards = [
  {
    eyebrow: "Stranded supply",
    title: "Curtailment leaves usable wind energy idle.",
    body: "Germany is tightening renewable compute obligations while record wind curtailment and negative-price hours expose post-EEG operators to weak merchant revenue.",
    metric: "573",
    metricLabel: "negative-price hours highlighted in the blueprint",
    tone: "sage",
  },
  {
    eyebrow: "Mandated demand",
    title: "Green-compute buyers need proof, not broad claims.",
    body: "EnEfG and CSRD pressure push data workloads toward renewable electricity with credible Scope 2 reconciliation and auditable matching.",
    metric: "2027",
    metricLabel: "renewable electricity mandate trigger for new data centers",
    tone: "amber",
  },
  {
    eyebrow: "Missing bridge",
    title: "Generic compute does not solve provenance.",
    body: "The gap is not raw GPU supply. It is a physical, workload-level link between renewable generation, dispatch decisions, and audit-ready evidence.",
    metric: "1:1",
    metricLabel: "physical link between wind supply and workload execution",
    tone: "navy",
  },
];

const storyBeats = [
  {
    kicker: "Source",
    title: "Post-EEG Onshore Wind Turbine",
    body: "Aging onshore turbines exiting fixed support can still provide valuable local renewable supply when a new behind-the-meter load is placed nearby.",
  },
  {
    kicker: "Connection",
    title: "Behind-the-meter private wire",
    body: "The private wire routes physical energy directly into the compute load, creating the foundation for measurable provenance.",
  },
  {
    kicker: "Load",
    title: "Immersion-cooled GPU container",
    body: "A compact containerized compute module turns intermittent wind into managed batch capacity without requiring hyperscale campus economics.",
  },
  {
    kicker: "Evidence",
    title: "Physical renewable provenance per workload",
    body: "Routing and dispatch metadata become the basis for machine-readable Scope 2 evidence attached to the actual workload.",
  },
  {
    kicker: "Replication",
    title: "A repeatable site pattern",
    body: "The same turbine-container unit can be replicated across suitable wind sites, creating a distributed pool of compliance-grade compute.",
  },
  {
    kicker: "System",
    title: "Physical wind supply meets data demand",
    body: "WindCore connects stranded renewable supply to compute demand through infrastructure, orchestration, and embedded auditability.",
  },
];

const provenancePoints = [
  {
    title: "Physical provenance",
    body: "Supply is tied to a real wind asset and local connection rather than a portfolio-level renewable claim.",
  },
  {
    title: "Embedded auditability",
    body: "The evidence layer is generated by the routing and orchestration workflow instead of manual post-hoc reconciliation.",
  },
  {
    title: "Compliance-grade compute",
    body: "The offer is not just GPU capacity. It is compute with renewable traceability built into the architecture.",
  },
];

const orchestrationSteps = [
  "Workload queue",
  "Wind forecast",
  "Spot signal",
  "Dispatch decision",
  "Scope 2 evidence",
];

const summaryCards = [
  {
    title: "Supply",
    body: "Post-EEG wind sites with constrained or under-monetized renewable output.",
    accent: "sage",
  },
  {
    title: "Connection",
    body: "Behind-the-meter private wire links the wind asset to the local compute module.",
    accent: "navy",
  },
  {
    title: "Compute",
    body: "Containerized GPU capacity targets batchable workloads with flexible timing.",
    accent: "amber",
  },
  {
    title: "Provenance",
    body: "Per-workload physical matching and audit evidence are generated as part of execution.",
    accent: "sage",
  },
  {
    title: "Customer Fit",
    body: "Best suited for rendering, simulation, AI tuning, and enterprises under ESG scrutiny.",
    accent: "rust",
  },
  {
    title: "Why It Matters",
    body: "WindCore turns otherwise stranded renewable energy into a compliance-ready compute product.",
    accent: "navy",
  },
];

export {
  ctaHref,
  heroStats,
  navLinks,
  orchestrationSteps,
  problemCards,
  provenancePoints,
  storyBeats,
  summaryCards,
};
